#pipeline name
name: docker_deployment

#Trigger that execute this pipeline when new push event occurs
on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sakthi2706
          password: dckr_pat_h8HTqrMR17AadojQwOmEwh7SzZI
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: sakthi2706/sakthi.flask.app:latest